### ISSUE TITLE
to_eights should be to_eighths

### ISSUE THREAD

**Issue by neilb** [p5-number-fraction/number-fraction#11]
You have functions `to_thirds`, `to_sixths`, but instead of `to_eighths` you have `to_eights`.

I think you should make it `to_eighths`, but retain `to_eights` for backwards compat.

**Comment by davorg** [comment]
Totally agree. See 21eb5771762940185803628f6d96887c649f7633

But I'm fascinated to hear how you found it. Are you using the module?

**Comment by neilb** [comment]
I was reading through the documentation, and "eights" leapt out at me :-)

**Comment by vanHoesel** [comment]
That is what you get when a non-native english speaking programmer starts writing code, but even in dutch, I would probably have made the same mistake "naar_achtsten"

@davorg , still nobody using it ? At least I am still using fractions in normal writing :-)

**Comment by davorg** [comment]
@vanHoesel: I've just seen it's being used by [Music::Intervals](https://metacpan.org/release/Music-Intervals); which looks cool.
